### ISSUE TITLE
multi workers and socket.ok

### ISSUE THREAD

**Issue by tarnazar** [geddy/geddy#415]
Hi all. When i use socket.io with 1 worker then all is works fine. But when i run geddy with 2 or more workers, then socket.io all the time disconnected -> reconnected -> online and again disconnected, like a infinite loop. I found in google some examples about socket.io + express + cluster, but i can't understand how can i run geddy with socket.io with multiply workers. And can it be realized without Redis ? Can someone help me ? 
Thanks.

**Comment by der-On** [comment]
@tarnazar I've added geddy.config.workerNumber in cb3efa3f21ad78fb634e0d672123825fb2f1571c

and I added support for a broadcast message that can be send from one worker to all others in f91016aae8575fedab34803fae0b346162b62fa6

You can dispatch a broadcast message as follows:

```javascrtipt
geddy.worker.sendMessage({ workerId: process.pid, method: 'broadcast', [aditional data...] });
```

and recieve the message as follows:

```javascript
process.addListener('message', function (msg) { ... });
```

**Comment by tarnazar** [comment]
Great, Thanks!
