### ISSUE TITLE
Depth of JSON objects returned with controller's .respond

### ISSUE THREAD

**Issue by akanieski** [geddy/geddy#449]
It seems that when I send a collection of items with nested JSON objects in each item in the array, by the time they are sent to the clientside they are missing the nested JSON.objects. See my example below.

Controller:

``` javascript
this.show = function (req, resp, params) {
  var list = [ 
    { name: 'foo', comments: ['foo','bar'] } , 
    { name: 'bar', comments: ['foo','bar'] } ,
  ];

  this.respond({params: params, list: list});
}
```

Clientside Result:

``` javascript
{
  params: { ... } ,
  list: [
    { name: 'foo' },
    { name: 'bar' }
  ]
}
```

Is there something I am doing wrong?

**Comment by strifan** [comment]
eems nothing has been changed, still not generated json for nested associations

current version is 13.0.7
