### ISSUE TITLE
Custom collection definition in model

### ISSUE THREAD

**Issue by mvmaasakkers** [geddy/geddy#502]
Is it possible to scaffold a model and define a custom (already existing mongodb) collection to it?

**Comment by mvmaasakkers** [comment]
Allright... seeing as 7 years have past I'm closing this issue now. Sorry for letting it open so long.

**Comment by ckhatton** [comment]
No worries mate 😊

**Comment by mde** [comment]
Sorry that your long years of waiting didn't pay off. :) Best wishes to you.

**Comment by mvmaasakkers** [comment]
Same to you!
