### ISSUE TITLE
Support for Redis

### ISSUE THREAD

**Issue by nicekiwi** [geddy/geddy#643]
MongoDB is great, but support for Redis would be awesome too. xD

http://redis.io <-- Website
https://github.com/maritz/nohm <-- Existing ORM for Redis and NodeJS
https://github.com/mranney/node_redis <-- Redis client for NodeJS

**Comment by der-On** [comment]
This should be moved into https://github.com/geddy/model I guess you could take the mongo adapter copy it and adjust it to work with redis.

**Comment by mde** [comment]
I would love a PR that implements this. It would be pretty easy to adapt the in-memory adapter. It's basically just stuffing JS objects into memory, and querying via M/R. The LevelDB adapter is also similar.

I've opened this issue in the Model project (https://github.com/geddy/model/issues/253) and will close this one here.
