### ISSUE TITLE
Where is the source of the docs

### ISSUE THREAD

**Issue by mehulkar** [geddy/geddy#644]
I found a typo in the guide and wanted to fix it, but I don't know where to submit a PR. 

Don't see a gh-pages branch on this repo and https://github.com/geddy/docs is empty. 

The Architecture config section refers to `config/environments.js` and I believe it should be `config/environment.js` (singular).

**Comment by der-On** [comment]
Guess this is what you are looking for: https://github.com/geddy/geddy/tree/master/docs

**Comment by mehulkar** [comment]
Sounds right. No idea what typo I was looking 6 months ago though :smile:
