### ISSUE TITLE
Geddy should use $NODE_ENV for environment

### ISSUE THREAD

**Issue by flyswatter** [geddy/geddy#653]
If the `$NODE_ENV` environment variable is set, geddy should adopt it.  It's accessible at `process.env.NODE_ENV`.

**Comment by der-On** [comment]
If you like, please make a PR on this. I guess it should not be so difficult as it is somewhere in the master cluster code of geddy.

**Comment by mde** [comment]
It already does this: https://github.com/geddy/geddy/blob/master/lib/config.js#L30
