### ISSUE TITLE
Many links on the geddyjs.org are throwing 500

### ISSUE THREAD

**Issue by kylehayes** [geddy/geddy#677]
http://geddyjs.org/reference
http://geddyjs.org/guide
http://geddyjs.org/tutorial
http://geddyjs.org/changelog

**Comment by mde** [comment]
Thank you. I'll take a look and see what's up.

**Comment by mde** [comment]
Fixed in 69633b6287475458ef89ce5a2354a488efd24f4e. Thanks for catching this!
