### ISSUE TITLE
Secrets,json file name should be come from env config.

### ISSUE THREAD

**Issue by devesh-anktech** [geddy/geddy#711]
Secrets,json file name should be come from env config.
currently it is hard coded in lib/config.js as 
`secretsFile = path.join(dir, 'config', 'secrets.json')`

This should come from config and if it is undefined in config then it should pick secrets.json  as default.

**Comment by AlexRaylight** [comment]
As a workaround, you can put the values themselves in the env, and then load them in the config with EJS.

Example from the deployment doc page:

```
{
  "passport": {
    "loginPath": "/login",
    "successRedirect": "/",
    "failureRedirect": "/login?failed=true",
    "twitter": {
      "consumerKey": "<%= process.env.TWITTER_KEY %>",
      "consumerSecret": "<%= process.env.TWITTER_SECRET %>"
    },
    "facebook": {
      "clientID": "<%= process.env.FACEBOOK_ID %>",
      "clientSecret": "<%= process.env.FACEBOOK_SECRET %>"
    }
  },
  "secret":"<%= process.env.GEDDY_SECRET %>"
}
```

**Comment by devesh-anktech** [comment]
Yeah @AlexRaylight  

I am using this now. 
Thanks for the reply.
