### ISSUE TITLE
Geddy setHeader('Access-Control-Allow-Origin','*')?

### ISSUE THREAD

**Issue by shangdev** [geddy/geddy#718]
I want send ajax request,but have a error:::::XMLHttpRequest cannot load http://localhost:4000/home/tieba. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8016' is therefore not allowed access.
how can I set r('Access-Control-Allow-Origin','*')?

**Comment by mde** [comment]
There is a thread on the mailing list about how to do CORS with Geddy: https://groups.google.com/forum/#!topic/geddyjs/7wodowJ2hlI
