### ISSUE TITLE
README.md needs to state "Up to Node v5"

### ISSUE THREAD

**Issue by ckhatton** [geddy/geddy#723]
The README needs to state that Geddy only works up to Node version 5.12.0. Errors persist in the newer versions 6 and 7.

Sad that no one wants to put time into updating the framework :cry:

**Comment by mde** [comment]
Heya, I've invited you as a contributor. I have been totally submerged at work, and haven't had the time, but I'd be happy to carve out some time if folks like you are interested in pitching in. :)

**Comment by ckhatton** [comment]
Okay thanks. I will update the README.md, but in terms of fixing the errors for Node v6+ it is a bit over my head :pensive:

Do I have to fork the repo and then create a pull request?

**Comment by mde** [comment]
Anything you do helps get the ball rolling. :) Yes, just fork the repo, then create a PR. Thanks!

**Comment by ckhatton** [comment]
Ok cool. And great work so far, (including others) I can see you've put a lot of time into it!
