### ISSUE TITLE
Todo Tutorial, Code Duplication

### ISSUE THREAD

**Issue by lazaridis-com** [geddy/geddy#733]
I just created the todo tutorial, which was easy and straightforward (from the command-line).

Now, the `todo` Entity (or model, or class) appears 2 times:

`app/models/todo.js`

and

`public/js/core/models.js`

Why this code-duplication?

**Comment by lazaridis-com** [comment]
@mde

**Comment by mde** [comment]
One of the files is the server-side JS code, the other is the client-side JS code.
