### ISSUE TITLE
translate the docs into chinese

### ISSUE THREAD

**Issue by jaycie** [geddy/geddy#735]
May I can help to translate the docs into chinese?

**Comment by mde** [comment]
That would be awesome! The docs for the site are here: https://github.com/geddy/geddy/tree/master/docs

You could start by forking the repo, moving the current docs into an `en-us` subdirectory, and then creating all the same docs in a `zh-cn` subdirectory. Does that seem reasonable?

**Comment by jaycie** [comment]
done, see [https://github.com/geddy/geddy/tree/master/docs/zh-cn](https://github.com/geddy/geddy/tree/master/docs/zh-cn )

**Comment by ckhatton** [comment]
Oh wow! 👏
