### ISSUE TITLE
Bug in serving static assets

### ISSUE THREAD

**Issue by evan3334** [geddy/geddy#743]
I've found a bug in the coding of Geddy's static asset serving system.

On [line 155 of lib/response/index.js](https://github.com/geddy/geddy/blob/master/lib/response/index.js#L155) there is a call to `fs.read` that throws an error because a call to `fs.read` requires a buffer to be passed as an argument in the recent versions of Node. The callback structure is also different, requiring a buffer parameter.

This bug causes no static assets to be served because this error is thrown every time the file is read from disk.

**Comment by evan3334** [comment]
I think it has something to do with Geddy being written for an older version of Node where the parameters for built-in methods are different. Geddy doesn't look like it's still being developed so I would think the only workaround would be using an old version of Node.
Personally, I switched to Sails.JS after encountering this issue because my project was still in an early stage and the switch wasn't that hard.

**Comment by AxDSan** [comment]
Nvm, duplicate of https://github.com/geddy/geddy/issues/736 - I tried that and it worked like a charm 👍

**Comment by evan3334** [comment]
Seems like they didn't actually make any change to the codebase after that issue was posted, creator mentioned making a fix but maybe didn't get around to it. Since that issue's still open and I've found a solution I'll just close this

**Comment by mde** [comment]
Apologies, Geddy is effectively in maintenance mode -- I believe we have some changes in master to fix this but they weren't pushed to NPM in a release. I finally got tests passing, and have pushed out v14.0.1. I hope this fixes the issue for you.
